DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Muistiinpano CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS RyhmaMuistiinpano CASCADE;
DROP TABLE IF EXISTS Kayt_Ryhma CASCADE;